# Generated by Django 5.2 on 2026-04-08 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kunde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kd_num', models.IntegerField(max_length=20)),
                ('kd_name', models.CharField(max_length=100)),
                ('kd_ansprechpartner', models.CharField(blank=True, max_length=100, null=True)),
                ('kd_plz', models.IntegerField(max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
